# KrekelEtAl2004-Wilmott-BasketOption

### Paper Information
Krekel, M., de Kock, J., Korn, R., & Man, T.-K. (2004). __An analysis of pricing methods for basket options__. Wilmott Magazine, 2004(7), 82–89.

### Abstract
This paper deals with the task of pricing basket options. Here, the main problem is not path-dependency but the multi-dimensionality which makes it impossible to give exact analytical representations of the option price. We review the literature and compare six different methods in a systematic way. Thereby we also look at the influence of various parameters such as strike, correlation, forwards or volatilities on the performance of the different approximations.

### Keywords and Phrases
Exotic options, basket options, numerical methods

## Note
* `Levy`, `MP-RG`, and `MP-4M` methods are currently available

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
import os

### Uncomment below if you want to run on your own modified code
#import sys
#sys.path.insert(sys.path.index('')+1, 'D:/Github/PyFENG')
import pyfeng as pf

In [3]:
texp = 5
rho = 0.5
o4 = np.ones(4)
sigma = o4 * 0.4
file = 'KrekelEtAl2004-Wilmott-BasketOption.xlsx'

# Table 1
## Changing Correlation

In [4]:
df = pd.read_excel(file, sheet_name='1')
df

Cor  Beisser  Gentle     Ju   Levy  MP-RG  MP-4M  MC-CV  StdDEv    Exact
0  0.10    20.12   15.36  21.77  22.06  20.25  21.36  21.62  0.0319  21.6921
1  0.30    24.21   19.62  25.05  25.17  22.54  24.91  24.97  0.0249  25.0293
2  0.50    27.63   23.78  28.01  28.05  24.50  27.98  27.97  0.0187  28.0074
3  0.70    30.62   27.98  30.74  30.75  26.18  30.74  30.72  0.0123  30.7427
4  0.80    31.99   30.13  32.04  32.04  26.93  32.04  32.03  0.0087  32.0412
5  0.95    33.92   33.41  33.92  33.92  27.97  33.92  33.92  0.0024  33.9187

In [5]:
rhos = [0.1, 0.3, 0.5, 0.7, 0.8, 0.95]
result = np.zeros_like(rhos)
for k in range(len(rhos)):
    m = pf.BsmBasketLowerBound(sigma=sigma, cor=rhos[k])
    result[k] = np.round(m.price(100, 100*o4, texp), 2)
np.round(result, 2), np.round(result, 2) - df['Beisser'].values

(array([20.12, 24.21, 27.63, 30.62, 31.99, 33.92]),
 array([0., 0., 0., 0., 0., 0.]))

In [6]:
rhos = [0.1, 0.3, 0.5, 0.7, 0.8, 0.95]
result = np.zeros_like(rhos)
for k in range(len(rhos)):
    m = pf.BsmBasketLevy1992(sigma=sigma, cor=rhos[k])
    result[k] = np.round(m.price(100, 100*o4, texp), 2)
np.round(result, 2), np.round(result, 2) - df['Levy'].values

(array([22.06, 25.17, 28.05, 30.75, 32.04, 33.92]),
 array([0., 0., 0., 0., 0., 0.]))

In [7]:
rhos = [0.1, 0.3, 0.5, 0.7, 0.8, 0.95]
result = np.zeros_like(rhos)
for k in range(len(rhos)):
    m = pf.BsmBasketMilevsky1998(sigma=sigma, cor=rhos[k])
    result[k] = np.round(m.price(100, 100*o4, texp), 2)
np.round(result, 2), np.round(result, 2) - df['MP-RG'].values

(array([20.25, 22.54, 24.5 , 26.18, 26.93, 27.97]),
 array([0., 0., 0., 0., 0., 0.]))

In [8]:
rhos = [0.1, 0.3, 0.5, 0.7, 0.8, 0.95]
result = np.zeros_like(rhos)
for k in range(len(rhos)):
    m = pf.BsmBasketJsu(sigma=sigma, cor=rhos[k])
    result[k] = np.round(m.price(100, 100*o4, texp), 2)
np.round(result, 2), np.round(result, 2) - df['MP-4M'].values

(array([21.36, 24.91, 27.98, 30.74, 32.04, 33.92]),
 array([0., 0., 0., 0., 0., 0.]))

# Table 2
## Changing Strike

In [9]:
df = pd.read_excel(file, sheet_name='2')
df

K  Beisser  Gentle     Ju   Levy  MP-RG  MP-4M  MC-CV  StdDev    Exact
0    50    54.16   51.99  54.31  54.34  51.93  54.35  54.28  0.0383  54.3102
1    60    47.27   44.43  47.48  47.52  44.41  47.50  47.45  0.0375  47.4811
2    70    41.26   37.93  41.52  41.57  38.01  41.53  41.50  0.0369  41.5225
3    80    36.04   32.40  36.36  36.40  32.68  36.34  36.52  0.0363  36.3518
4    90    31.53   27.73  31.88  31.92  28.22  31.86  31.85  0.0356  31.8768
5   100    27.63   23.78  28.01  28.05  24.50  27.98  27.98  0.0350  28.0074
6   110    24.27   20.46  24.67  24.70  21.39  24.63  24.63  0.0344  24.6605
7   120    21.36   17.65  21.77  21.80  18.77  21.73  21.74  0.0338  21.7626
8   130    18.84   15.27  19.26  19.28  16.57  19.22  19.22  0.0332  19.2493
9   140    16.65   13.25  17.07  17.10  14.70  17.04  17.05  0.0326  17.0655
10  150    14.75   11.53  15.17  15.19  13.10  15.14  15.15  0.0320  15.1640

In [10]:
strike = np.arange(50, 151, 10)
m = pf.BsmBasketLowerBound(sigma=sigma, cor=0.5)
result = m.price(strike, spot=100*o4, texp=texp)
np.round(result, 2), np.round(result, 2) - df['Beisser'].values

(array([54.16, 47.27, 41.26, 36.04, 31.53, 27.63, 24.27, 21.36, 18.84,
        16.65, 14.75]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [11]:
strike = np.arange(50, 151, 10)
m = pf.BsmBasketLevy1992(sigma=sigma, cor=0.5)
result = m.price(strike, spot=100*o4, texp=texp)
np.round(result, 2), np.round(result, 2) - df['Levy'].values

(array([54.34, 47.52, 41.57, 36.4 , 31.92, 28.05, 24.7 , 21.8 , 19.28,
        17.1 , 15.19]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [12]:
m = pf.BsmBasketMilevsky1998(sigma=sigma, cor=0.5)
result = m.price(strike, spot=100*o4, texp=texp)
np.round(result, 2), np.round(result, 2) - df['MP-RG'].values

(array([51.93, 44.41, 38.03, 32.68, 28.22, 24.5 , 21.39, 18.77, 16.57,
        14.7 , 13.1 ]),
 array([0.  , 0.  , 0.02, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]))

In [13]:
m = pf.BsmBasketJsu(sigma=sigma, cor=0.5)
result = m.price(strike, spot=100*o4, texp=texp)
np.round(result, 2), np.round(result, 2) - df['MP-4M'].values

(array([54.35, 47.5 , 41.53, 36.34, 31.86, 27.98, 24.63, 21.73, 19.22,
        17.04, 15.14]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

# Table 3
## Changing Forward

In [14]:
df = pd.read_excel(file, sheet_name='3')
df

F  Beisser  Gentle     Ju   Levy  MP-RG  MP-4M  MC-CV  StdDev
0    50     4.16    3.00   4.34   4.34   3.93   4.33   4.34  0.0141
1    60     7.27    5.53   7.51   7.52   6.56   7.50   7.50  0.0185
2    70    11.26    8.91  11.55  11.57   9.95  11.53  11.53  0.0227
3    80    16.04   13.13  16.37  16.40  14.10  16.34  16.35  0.0268
4    90    21.53   18.11  21.89  21.92  18.97  21.86  21.86  0.0309
5   100    27.63   23.78  28.01  28.05  24.50  27.98  27.98  0.0350
6   110    34.27   30.08  34.66  34.70  30.63  34.63  34.63  0.0391
7   120    41.36   36.91  41.75  41.80  37.32  41.73  41.71  0.0433
8   130    48.84   44.21  49.23  49.28  44.49  49.21  49.19  0.0474
9   140    56.65   51.92  57.04  57.10  52.08  57.03  57.00  0.0516
10  150    64.75   59.98  65.13  65.19  60.05  65.14  65.08  0.0556

In [15]:
spot = np.arange(50., 151., 10)[:,None]*np.ones(4)
result = np.zeros_like(spot[:, 0], dtype=float)
for i in range(len(spot[:, 0])):
    m = pf.BsmBasketLowerBound(sigma=sigma, cor = 0.5)
    result[i] = m.price(100, spot[i], texp)
np.round(result, 2), np.round(result, 2) - df['Beisser'].values

(array([ 4.16,  7.27, 11.26, 16.04, 21.53, 27.63, 34.27, 41.36, 48.84,
        56.65, 64.75]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [16]:
spot = np.arange(50, 151, 10)[:,None]*np.ones(4)
m = pf.BsmBasketLevy1992(sigma=sigma, cor=0.5)
result = m.price(100, spot=spot, texp=texp)
np.round(result, 2), np.round(result, 2) - df['Levy'].values

(array([ 4.34,  7.52, 11.57, 16.4 , 21.92, 28.05, 34.7 , 41.8 , 49.28,
        57.1 , 65.19]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [17]:
spot = np.arange(50, 151, 10)[:,None]*np.ones(4)
m = pf.BsmBasketMilevsky1998(sigma=sigma, cor=0.5)
result = m.price(100, spot=spot, texp=texp)
np.round(result, 2), np.round(result, 2) - df['MP-RG'].values

(array([ 3.93,  6.56,  9.95, 14.1 , 18.97, 24.5 , 30.63, 37.32, 44.49,
        52.08, 60.05]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [18]:
spot = np.arange(50., 151., 10)[:,None]*np.ones(4)
result = np.zeros_like(spot[:, 0], dtype=float)
for i in range(len(spot[:, 0])):
    m = pf.BsmBasketJsu(sigma=sigma, cor = 0.5)
    result[i] = m.price(100, spot[i], texp)
np.round(result, 2), np.round(result, 2) - df['MP-4M'].values

(array([ 4.33,  7.5 , 11.53, 16.34, 21.86, 27.98, 34.63, 41.73, 49.21,
        57.03, 65.14]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

# Table 4
## Changing all volatilities

In [19]:
df = pd.read_excel(file, sheet_name='4')
df

Sigma  Beisser  Gentle     Ju   Levy  MP-RG  MP-4M  MC-CV  StdDev    Exact
0    0.05     3.53    3.52   3.53   3.53   3.52   3.53   3.53  0.0014   3.5259
1    0.10     7.04    6.98   7.05   7.05   6.99   7.05   7.05  0.0042   7.0498
2    0.15    10.55   10.33  10.57  10.57  10.36  10.57  10.57  0.0073  10.5696
3    0.20    14.03   13.52  14.08  14.08  13.59  14.08  14.08  0.0115  14.0830
4    0.30    20.91   19.22  21.08  21.09  19.49  21.07  21.07  0.0237  21.0787
5    0.40    27.63   23.78  28.01  28.05  24.50  27.98  27.98  0.0350  28.0074
6    0.50    34.15   27.01  34.84  34.96  28.51  34.73  34.80  0.0448  34.8289
7    0.60    40.41   28.84  41.52  41.78  31.56  41.19  41.44  0.0327  41.4931
8    0.70    46.39   29.30  47.97  48.50  33.72  46.23  47.86  0.0490  47.9430
9    0.80    52.05   28.57  54.09  55.05  35.15  48.39  54.01  0.0685  54.1192
10   1.00    62.32   24.41  64.93  67.24  36.45  47.90  65.31  0.0996  65.4256

In [20]:
sigmas = np.array([5, 10, 15, 20, 30, 40, 50, 60, 70, 80, 100])/100
result = np.zeros_like(sigmas)
for k in range(len(sigmas)):
    m = pf.BsmBasketLowerBound(sigma=sigmas[k]*o4, cor=0.5)
    result[k] = m.price(100, 100*o4, texp)
np.round(result, 2), np.round(result, 2) - df['Beisser'].values

(array([ 3.53,  7.04, 10.55, 14.03, 20.91, 27.63, 34.15, 40.41, 46.39,
        52.05, 62.32]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [21]:
sigmas = np.array([5, 10, 15, 20, 30, 40, 50, 60, 70, 80, 100])/100
result = np.zeros_like(sigmas)
for k in range(len(sigmas)):
    m = pf.BsmBasketLevy1992(sigma=sigmas[k]*o4, cor=0.5)
    result[k] = m.price(100, 100*o4, texp)
np.round(result, 2), np.round(result, 2) - df['Levy'].values

(array([ 3.53,  7.05, 10.57, 14.08, 21.09, 28.05, 34.96, 41.78, 48.5 ,
        55.05, 67.24]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [22]:
sigmas = np.array([5, 10, 15, 20, 30, 40, 50, 60, 70, 80, 100])/100
result = np.zeros_like(sigmas)
for k in range(len(sigmas)):
    m = pf.BsmBasketMilevsky1998(sigma=sigmas[k]*o4, cor=0.5)
    result[k] = m.price(100, 100*o4, texp)
np.round(result, 2), np.round(result, 2) - df['MP-RG'].values

(array([ 3.52,  6.99, 10.36, 13.59, 19.49, 24.5 , 28.51, 31.56, 33.72,
        35.15, 36.45]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [23]:
sigmas = np.array([5, 10, 15, 20, 30, 40, 50, 60, 70, 80, 100])/100
result = np.zeros_like(sigmas)
for k in range(len(sigmas)):
    m = pf.BsmBasketJsu(sigma=sigmas[k]*o4, cor=0.5)
    result[k] = m.price(100, 100*o4, texp)
np.round(result, 2), np.round(result, 2) - df['MP-4M'].values

(array([ 3.53,  7.05, 10.57, 14.08, 21.07, 27.98, 34.73, 41.19, 46.23,
        48.39, 47.9 ]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

# Table 5
## Changing the other volatilities with (sigma_1=1)

In [24]:
df = pd.read_excel(file, sheet_name='5')
df

Sigma  Beisser  Gentle     Ju   Levy  MP-RG  MP-4M  MC-CV  StdDev    Exact
0    0.05    19.45   15.15  35.59  55.56  35.22  18.51  22.65  0.5594  19.4591
1    0.10    20.84   16.60  36.19  55.52  35.23  18.64  21.30  0.3858  20.9682
2    0.15    22.60   18.08  36.93  55.61  35.24  18.81  22.94  0.2660  23.0042
3    0.20    24.69   19.56  37.80  55.71  35.26  19.01  25.24  0.2124  25.3794
4    0.30    29.52   22.35  39.97  55.98  35.30  19.42  30.95  0.1603  30.6027
5    0.40    34.72   24.73  42.66  56.35  35.36  20.37  36.89  0.1156  36.0485
6    0.50    39.96   26.52  45.84  56.89  35.44  20.60  41.72  0.0894  41.4943
7    0.60    45.05   27.59  49.39  57.68  35.56  21.72  46.68  0.0472  46.8189
8    0.70    49.88   27.87  53.21  58.87  35.72  23.66  51.78  0.0587  51.9361
9    0.80    54.39   27.38  57.17  60.70  35.93  27.38  56.61  0.0742  56.7772
10   1.00    62.32   24.41  64.93  67.24  36.45  47.90  65.31  0.0996  65.4256

In [25]:
sigmas = np.array([5, 10, 15, 20, 30, 40, 50, 60, 70, 80, 100])/100
result = np.zeros_like(sigmas)
for k in range(len(sigmas)):
    sigma_asym = np.array([sigmas[k], sigmas[k], sigmas[k], 1])
    m = pf.BsmBasketLowerBound(sigma=sigma_asym, cor=0.5)
    result[k] = m.price(100, 100*o4, texp)
np.round(result, 2), np.round(result, 2) - df['Beisser'].values

(array([19.45, 20.84, 22.6 , 24.69, 29.52, 34.72, 39.96, 45.05, 49.88,
        54.39, 62.32]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [26]:
sigmas = np.array([5, 10, 15, 20, 30, 40, 50, 60, 70, 80, 100])/100
result = np.zeros_like(sigmas)
for k in range(len(sigmas)):
    sigma_asym = np.array([sigmas[k], sigmas[k], sigmas[k], 1])
    m = pf.BsmBasketLevy1992(sigma=sigma_asym, cor=0.5)
    result[k] = m.price(100, 100*o4, texp)
np.round(result, 2), np.round(result, 2) - df['Levy'].values

(array([55.46, 55.52, 55.61, 55.71, 55.98, 56.35, 56.89, 57.68, 58.87,
        60.7 , 67.24]),
 array([-0.1,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ]))

In [27]:
sigmas = np.array([5, 10, 15, 20, 30, 40, 50, 60, 70, 80, 100])/100
result = np.zeros_like(sigmas)
for k in range(len(sigmas)):
    sigma_asym = np.array([sigmas[k], sigmas[k], sigmas[k], 1])
    m = pf.BsmBasketMilevsky1998(sigma=sigma_asym, cor=0.5)
    result[k] = m.price(100, 100*o4, texp)
np.round(result, 2), np.round(result, 2) - df['MP-RG'].values

(array([35.22, 35.23, 35.24, 35.26, 35.3 , 35.36, 35.44, 35.56, 35.72,
        35.93, 36.45]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [28]:
sigmas = np.array([5, 10, 15, 20, 30, 40, 50, 60, 70, 80, 100])/100
result = np.zeros_like(sigmas)
for k in range(len(sigmas)):
    sigma_asym = np.array([sigmas[k], sigmas[k], sigmas[k], 1])
    m = pf.BsmBasketJsu(sigma=sigma_asym, cor=0.5)
    result[k] = m.price(100, 100*o4, texp)
np.round(result, 2), np.round(result, 2) - df['MP-4M'].values

(array([18.64, 18.78, 18.92, 19.07, 19.42, 19.9 , 20.6 , 21.72, 23.66,
        27.38, 47.9 ]),
 array([ 0.13,  0.14,  0.11,  0.06,  0.  , -0.47,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ]))